import { StyleSheet } from "react-native";
import { colors, typography } from "./tokens";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundOrbLarge: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: colors.patternPrimary,
    bottom: -30,
    left: 84,
  },
  backgroundOrbSmall: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: colors.patternSecondary,
    bottom: -10,
    right: -10,
  },
  container: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: colors.background,
  },
  sidebar: {
    width: 59,
    backgroundColor: colors.homeSidebar,
    alignItems: "center",
    paddingTop: 20,
  },
  closeButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 34,
  },
  menuLine: {
    width: 22,
    height: 2.5,
    borderRadius: 999,
    backgroundColor: colors.white,
    marginBottom: 5,
  },
  sidebarActions: {
    gap: 16,
    marginBottom: 190,
  },
  sidebarIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  addButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
    marginTop: "auto",
    marginBottom: 150,
  },
  main: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    height: 70,
    backgroundColor: colors.homeHeader,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
  },
  headerMenu: {
    width: 24,
    marginRight: 22,
  },
  headerTitle: {
    fontFamily: typography.fontFamily.inter,
    fontSize: 17,
    color: colors.textPrimary,
    letterSpacing: 2.8,
  },
  content: {
    paddingTop: 13,
    paddingHorizontal: 15,
  },
  todayCard: {
    width: "100%",
    height: 155,
    borderRadius: 14,
    backgroundColor: colors.homeCard,
    marginBottom: 12,
    paddingTop: 13,
    paddingHorizontal: 14,
    overflow: "hidden",
  },
  todayHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  todayBadge: {
    width: 22,
    height: 22,
    borderTopLeftRadius: 14,
    borderBottomRightRadius: 14,
    backgroundColor: colors.taskIndicator,
    marginRight: 18,
  },
  todayLabel: {
    fontFamily: typography.fontFamily.inter,
    fontSize: 16,
    color: colors.white,
    flex: 1,
  },
  taskBar: {
    width: 7,
    height: 24,
    borderRadius: 999,
    marginLeft: 4,
  },
  taskBarWarm: {
    backgroundColor: "#FFA219",
  },
  taskBarAmber: {
    backgroundColor: "#FFBF18",
  },
  taskBarOrange: {
    backgroundColor: "#FFDD33",
  },
  taskBarLime: {
    backgroundColor: "#C7FF1A",
  },
  taskBars: {
    flexDirection: "row",
    alignItems: "center",
  },
  taskTitle: {
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    fontFamily: typography.fontFamily.inter,
    maxWidth: 204,
    marginLeft: 43,
  },
  cardChevronLeft: {
    position: "absolute",
    left: 10,
    top: 74,
  },
  cardChevronRight: {
    position: "absolute",
    right: 10,
    top: 74,
  },
  progressBar: {
    position: "absolute",
    left: 52,
    bottom: 44,
    width: 68,
    height: 3,
    borderRadius: 999,
    backgroundColor: "#9DA2C2",
    opacity: 0.7,
  },
  todayButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 17,
  },
  todayButton: {
    width: 84,
    height: 29,
    borderRadius: 999,
    backgroundColor: colors.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  todayButtonText: {
    color: colors.textSecondary,
    fontSize: 9,
    fontFamily: typography.fontFamily.inter,
  },
  calendarLabels: {
    flexDirection: "row",
    marginBottom: 6,
  },
  calendarLabel: {
    width: 98,
    textAlign: "center",
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: typography.fontFamily.inter,
    marginRight: 25,
  },
  calendarRow: {
    flexDirection: "row",
    gap: 25,
  },
});
